### ISSUE TITLE
WebGL rendering is pretty slow, especially when pulling and rendering multiple streams

### ISSUE THREAD

**Issue by HLLTBag** [AgoraIO/Electron-SDK#14]
When rendering multiple streams, like 5 streams and above, there is obvious dropping frames (4FPS at worst), even all the stream is set to lowest resolution and FPS (120P). Performance profiles show bottle neck at function `uploadYuv`
![image](https://user-images.githubusercontent.com/11649044/43759073-bb746afe-9a50-11e8-9755-e2eaa94008f0.png)

I'm not pro at WebGL, and I'm wondering if there is any plans or suggestions on improving this.

Running at Electron v2.0.6, MacOS 10.13.3

**Comment by plutoless** [comment]
maybe try **setVideoRenderFps** and **setVideoRenderDimension** function.
For now webGL is the only option for electron sdk rendering. We are planning to add soft rendering for cases when webGL is not supported but i guess this will not help your case.

The performance bottleneck has been identified already, especially when you have multiple streams feeding data at the same time, the data frequency and size will boost and lead to performance issues mainly at JS level.

The solution is to provide above two methods so that we can control the video data feeding frequency and size already in C++ level. setVideoRenderFps can force C++ to feed data by given frequency (say we set fps to 10, for this stream, it's guaranteed to feed stream video data 10 times only per second ). setVideoRenderDimension can force C++ to feed scaled video data by given resolution.

When you have multiple streams on one screen, the common technique is to spend your resource on streams which are more important (i.e. screenshare, main camera), while for others you may choose to set low fps and dimension because user will barely pay attention to them.

Hope this helps.

**Comment by HLLTBag** [comment]
I think fixed FPS and resolution shouldn't be first workaround, it's more like backup plan and something. In addition, in my tests, webRTC soft rendering is better than WebGL rendering, I don't if it's expected.

**Comment by HLLTBag** [comment]
I think fixed FPS and resolution shouldn't be first workaround, it's more like backup plan and something. In addition, in my tests, webRTC soft rendering is better than WebGL rendering, I don't know if it's expected.

**Comment by plutoless** [comment]
closed as no more activity.
