### ISSUE TITLE
performance comparison between electron sdk and web (4.0 ng) sdk

### ISSUE THREAD

**Issue by 9oelM** [AgoraIO/Electron-SDK#429]
let's suppose that you are building an Electron app.

Theoretically, because eletron sdk uses c++ native modules, it could be faster, but of course there might be performance bottlenecks in communication between c++ and js layers. In this view, could it be possible that using [web sdk ng](https://agoraio-community.github.io/AgoraWebSDK-NG/) for an Electron app could be faster in terms of performance? But I am not sure how web sdk ng works in terms of performance, so I'm leaving this as a question.

Thank you.

**Comment by plutoless** [comment]
@9oelM websdk is using webrtc technologies so it's a browser built in tech and lots of performance optimizations have been done for it. while for electron you are right there will be performance bottlenecks in communication between c++ and js layers. however, the performance difference is not that apparent when you use regular resolution + not too many videos. the performance impact will be a little bit more significant when you are doing HD resolution or > 10 videos.
The good thing of the using websdk is it's all built in browser techs, it has lots of performance optimizations, and easy to use; while the side effect is the behavior could differ on different versions of browsers, and when there's problems/issues using webrtc (cannot open camera e.g.), it's hard to find root cause or fix bugs.
The good thing of using electron native sdk is it's using agora's native sdk - meaning all modules including capturing and encoding are all done by agora, so we are more confident when an issue happens we can most likely fix unless it's caused by system limitations. The side effect is performance impact as you mentioned.
So if you are going to do HD resolution scenario and you don't really care when webrtc has issues on some specific machines/browsers, it's recommended to use websdk. If you want more controls and all your users using the same environment + you want more agora specific features, then electron is the way to go.

hope this answers your question.

**Comment by 9oelM** [comment]
@plutoless wow, thank you for your detailed response. So just to confirm again.. if you want to publish/subscribe HD resolution on Electron, there is a high chance that web sdk will have performance wins over electron sdk, right?

**Comment by plutoless** [comment]
talking about performance only (i.e. HD 1080P or 4K), the simple answer is yes.
of course there will be some more relevant factors e.g. the codec you are using (vp8 or h264, one is software encoder and one is hardware)

**Comment by 9oelM** [comment]
thank you for your answer. I appreciate it 👍
